[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/contact"
  to = "/thank-you"
  status = 200
  conditions = {Success = ["true"]}

[forms]
  [forms.contact]
    success_url = "/thank-you"
